### ISSUE TITLE
getOSGBfromDec returns RangeError Exception

### ISSUE THREAD

**Issue by zachisit** [FunkyPenguin24/latlong_to_osgrid#1]
When using the `getOSGBfromDec` endpoint, I receive the following error:

_Invalid value: Not in inclusive range 0..1114111: -78_

I'm using the following lat/long values:

```
OSRef result = _converter.getOSGBfromDec(
    39.52251,
    -120.8139233
);
```

Upgrading Dart SDK from 2.7 to 2.10 does not resolve the problem.

These lat/longs are traditional types I thought. I then realized that I can pass in different `Datums` when calling this endpoint, but none of the available endpoints worked. What am I missing here?

**Comment by FunkyPenguin24** [comment]
Hi,

I can see the coordinates you're using are in the US. Unfortunately, the Ordnance Survey grid only covers the United Kingdom so coordinates from America produce results too far out of range. I should have made this clear in the readme, I'll write this into the package to make it clearer when the error is thrown, thanks for bringing this up and sorry for any confusion.

The different datums are to do with different coordinate systems around the world, if no datum is passed then the package uses WGS84, which is the default datum for GPS systems around the world.

**Comment by zachisit** [comment]
Ok thanks for the response. Two additional questions:

- So what package is available if I need to convert US cords?
- Why would the `getDegreeFromDecimal` endpoint seem to work fine?

**Comment by FunkyPenguin24** [comment]
From the best of my knowledge, I don't think the US has a unique coordinate system but if they do I'm not aware of it, I only know they use GPS coordinates like the ones you have provided.

The `getDegreeFromDecimal` endpoint works because it doesn't convert coordinates from latitude and longitude to OS Grid, it just converts latitude and longitude coordinates from their decimal format and their degrees, minutes and seconds format. As long as the coordinates you provide are legitimate, the function should work.
